-- Clario public database schema
create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.clients (
  id bigint generated by default as identity primary key,
  owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  name text not null,
  contact_name text default '', phone text default '', email text default '',
  address text default '', tax_id text default '', notes text default '',
  created_at timestamptz not null default now()
);

create table if not exists public.sales (
  id bigint generated by default as identity primary key,
  owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  name text not null, client_name text not null, client_id bigint references public.clients(id) on delete set null,
  base numeric(12,2) not null check (base > 0),
  irpf_enabled boolean not null default true, iva_enabled boolean not null default true,
  extra_rate numeric(6,3) not null default 0, description text default '', status text not null default 'active',
  created_at timestamptz not null default now()
);

create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  sale_id bigint not null references public.sales(id) on delete cascade,
  base numeric(12,2) not null check (base > 0), paid_at date not null default current_date,
  method text not null default 'Transferencia', notes text default '', created_at timestamptz not null default now()
);

create table if not exists public.expenses (
  id bigint generated by default as identity primary key,
  owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  name text not null, amount numeric(12,2) not null check (amount > 0),
  type text not null check (type in ('business','personal')), category text not null, subcategory text default '',
  method text not null default 'Tarjeta', deductible boolean not null default false,
  description text default '', recurring boolean not null default false,
  attachment_path text, attachment_name text, confirmed_at date not null default current_date,
  created_at timestamptz not null default now()
);

create table if not exists public.goals (
  id bigint generated by default as identity primary key,
  owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  name text not null, target numeric(12,2) not null check (target > 0), current numeric(12,2) not null default 0,
  term text not null default 'medium', created_at timestamptz not null default now()
);

create table if not exists public.budgets (
  id bigint generated by default as identity primary key,
  owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  type text not null check (type in ('business','personal')), category text not null,
  budget_limit numeric(12,2) not null check (budget_limit > 0), warning_percent integer not null default 80 check (warning_percent between 1 and 100),
  period text not null default 'monthly', created_at timestamptz not null default now(),
  unique(owner_id,type,category)
);

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$
begin insert into public.profiles(id,name) values(new.id,coalesce(new.raw_user_meta_data->>'name','')) on conflict(id) do nothing; return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.clients enable row level security;
alter table public.sales enable row level security;
alter table public.payments enable row level security;
alter table public.expenses enable row level security;
alter table public.goals enable row level security;
alter table public.budgets enable row level security;

drop policy if exists "profiles_own" on public.profiles;
drop policy if exists "clients_own" on public.clients;
drop policy if exists "sales_own" on public.sales;
drop policy if exists "payments_own" on public.payments;
drop policy if exists "expenses_own" on public.expenses;
drop policy if exists "goals_own" on public.goals;
drop policy if exists "budgets_own" on public.budgets;
drop policy if exists "receipts_read_own" on storage.objects;
drop policy if exists "receipts_insert_own" on storage.objects;
drop policy if exists "receipts_update_own" on storage.objects;
drop policy if exists "receipts_delete_own" on storage.objects;

create policy "profiles_own" on public.profiles for all using (id=auth.uid()) with check (id=auth.uid());
create policy "clients_own" on public.clients for all using (owner_id=auth.uid()) with check (owner_id=auth.uid());
create policy "sales_own" on public.sales for all using (owner_id=auth.uid()) with check (owner_id=auth.uid());
create policy "payments_own" on public.payments for all using (owner_id=auth.uid()) with check (owner_id=auth.uid());
create policy "expenses_own" on public.expenses for all using (owner_id=auth.uid()) with check (owner_id=auth.uid());
create policy "goals_own" on public.goals for all using (owner_id=auth.uid()) with check (owner_id=auth.uid());
create policy "budgets_own" on public.budgets for all using (owner_id=auth.uid()) with check (owner_id=auth.uid());

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values('receipts','receipts',false,5242880,array['image/jpeg','image/png','image/webp','application/pdf'])
on conflict(id) do update set public=false,file_size_limit=5242880;

create policy "receipts_read_own" on storage.objects for select using (bucket_id='receipts' and (storage.foldername(name))[1]=auth.uid()::text);
create policy "receipts_insert_own" on storage.objects for insert with check (bucket_id='receipts' and (storage.foldername(name))[1]=auth.uid()::text);
create policy "receipts_update_own" on storage.objects for update using (bucket_id='receipts' and (storage.foldername(name))[1]=auth.uid()::text);
create policy "receipts_delete_own" on storage.objects for delete using (bucket_id='receipts' and (storage.foldername(name))[1]=auth.uid()::text);

create index if not exists sales_owner_idx on public.sales(owner_id,created_at desc);
create index if not exists payments_owner_idx on public.payments(owner_id,paid_at desc);
create index if not exists expenses_owner_idx on public.expenses(owner_id,confirmed_at desc);
