-- Clario v3: privacidad por movimiento y notificaciones push.
-- Ejecutar una sola vez en Supabase SQL Editor.

alter table public.sales
  add column if not exists hidden_from uuid[] not null default '{}',
  add column if not exists next_payment_due date;

alter table public.payments
  add column if not exists hidden_from uuid[] not null default '{}';

alter table public.expenses
  add column if not exists hidden_from uuid[] not null default '{}';

alter table public.recurring_rules
  add column if not exists hidden_from uuid[] not null default '{}';

create or replace function public.can_view_movement(
  p_workspace uuid,
  p_hidden_from uuid[]
) returns boolean
language sql stable security definer set search_path=public as $$
  select coalesce(
    public.workspace_role(p_workspace) = 'owner'
    or (
      public.can_view_workspace(p_workspace)
      and not (auth.uid() = any(coalesce(p_hidden_from, '{}'::uuid[])))
    ),
    false
  )
$$;

drop policy if exists sales_view on public.sales;
create policy sales_view on public.sales for select
  using(public.can_view_movement(workspace_id, hidden_from));

drop policy if exists payments_view on public.payments;
create policy payments_view on public.payments for select
  using(public.can_view_movement(workspace_id, hidden_from));

drop policy if exists expenses_view on public.expenses;
create policy expenses_view on public.expenses for select
  using(public.can_view_movement(workspace_id, hidden_from));



drop policy if exists recurring_rules_view on public.recurring_rules;
drop policy if exists recurring_rules_manage on public.recurring_rules;
drop policy if exists recurring_rules_insert on public.recurring_rules;
drop policy if exists recurring_rules_update on public.recurring_rules;
drop policy if exists recurring_rules_delete on public.recurring_rules;
create policy recurring_rules_view on public.recurring_rules for select
  using(public.can_view_movement(workspace_id, hidden_from));
create policy recurring_rules_insert on public.recurring_rules for insert
  with check(public.can_edit_workspace(workspace_id));
create policy recurring_rules_update on public.recurring_rules for update
  using(public.can_edit_workspace(workspace_id))
  with check(public.can_edit_workspace(workspace_id));
create policy recurring_rules_delete on public.recurring_rules for delete
  using(public.can_edit_workspace(workspace_id));

create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  workspace_id uuid not null default public.current_workspace_id() references public.workspaces(id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth_key text not null,
  enabled boolean not null default true,
  last_notified_on date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.push_subscriptions enable row level security;

drop policy if exists push_subscriptions_own on public.push_subscriptions;
create policy push_subscriptions_own on public.push_subscriptions for all
  using(user_id=auth.uid())
  with check(user_id=auth.uid() and public.can_view_workspace(workspace_id));

create index if not exists push_subscriptions_workspace_idx
  on public.push_subscriptions(workspace_id, enabled);

create index if not exists sales_next_payment_due_idx
  on public.sales(workspace_id, next_payment_due)
  where next_payment_due is not null;
