-- Clario v2: equipos, categorias, modelos y gastos recurrentes
-- Ejecutar una sola vez en Supabase SQL Editor.
create extension if not exists pgcrypto;

alter table public.profiles add column if not exists email text default '';
alter table public.profiles add column if not exists active_workspace_id uuid;

create table if not exists public.workspaces (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  name text not null default 'Mi espacio Clario',
  created_at timestamptz not null default now()
);

create table if not exists public.workspace_members (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null check (role in ('owner','editor','viewer')),
  display_name text not null default '', email text not null default '',
  created_at timestamptz not null default now(),
  unique(workspace_id,user_id)
);

create table if not exists public.workspace_invitations (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  email text not null, role text not null check (role in ('editor','viewer')),
  token uuid not null default gen_random_uuid() unique,
  invited_by uuid not null default auth.uid() references auth.users(id) on delete cascade,
  accepted_at timestamptz, created_at timestamptz not null default now()
);

create or replace function public.workspace_role(p_workspace uuid) returns text
language sql stable security definer set search_path=public as $$
  select role from public.workspace_members where workspace_id=p_workspace and user_id=auth.uid() limit 1
$$;
create or replace function public.can_view_workspace(p_workspace uuid) returns boolean
language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.workspace_members where workspace_id=p_workspace and user_id=auth.uid())
$$;
create or replace function public.can_edit_workspace(p_workspace uuid) returns boolean
language sql stable security definer set search_path=public as $$
  select coalesce(public.workspace_role(p_workspace) in ('owner','editor'),false)
$$;
create or replace function public.can_manage_workspace(p_workspace uuid) returns boolean
language sql stable security definer set search_path=public as $$
  select coalesce(public.workspace_role(p_workspace)='owner',false)
$$;
create or replace function public.current_workspace_id() returns uuid
language sql stable security definer set search_path=public as $$
  select coalesce(
    (select active_workspace_id from public.profiles where id=auth.uid()),
    (select workspace_id from public.workspace_members where user_id=auth.uid() order by created_at limit 1)
  )
$$;

insert into public.workspaces(owner_id,name)
select p.id,case when coalesce(p.name,'')='' then 'Mi espacio Clario' else 'Clario de '||p.name end
from public.profiles p where not exists(select 1 from public.workspaces w where w.owner_id=p.id);
insert into public.workspace_members(workspace_id,user_id,role,display_name,email)
select w.id,w.owner_id,'owner',coalesce(p.name,''),coalesce(p.email,u.email,'')
from public.workspaces w left join public.profiles p on p.id=w.owner_id left join auth.users u on u.id=w.owner_id
on conflict(workspace_id,user_id) do update set role='owner';
update public.profiles p set email=coalesce(nullif(p.email,''),u.email,''),active_workspace_id=coalesce(p.active_workspace_id,w.id)
from auth.users u,public.workspaces w where u.id=p.id and w.owner_id=p.id;

alter table public.clients add column if not exists workspace_id uuid references public.workspaces(id) on delete cascade;
alter table public.sales add column if not exists workspace_id uuid references public.workspaces(id) on delete cascade;
alter table public.payments add column if not exists workspace_id uuid references public.workspaces(id) on delete cascade;
alter table public.expenses add column if not exists workspace_id uuid references public.workspaces(id) on delete cascade;
alter table public.goals add column if not exists workspace_id uuid references public.workspaces(id) on delete cascade;
alter table public.budgets add column if not exists workspace_id uuid references public.workspaces(id) on delete cascade;
update public.clients x set workspace_id=w.id from public.workspaces w where x.workspace_id is null and w.owner_id=x.owner_id;
update public.sales x set workspace_id=w.id from public.workspaces w where x.workspace_id is null and w.owner_id=x.owner_id;
update public.payments x set workspace_id=w.id from public.workspaces w where x.workspace_id is null and w.owner_id=x.owner_id;
update public.expenses x set workspace_id=w.id from public.workspaces w where x.workspace_id is null and w.owner_id=x.owner_id;
update public.goals x set workspace_id=w.id from public.workspaces w where x.workspace_id is null and w.owner_id=x.owner_id;
update public.budgets x set workspace_id=w.id from public.workspaces w where x.workspace_id is null and w.owner_id=x.owner_id;
alter table public.clients alter column workspace_id set default public.current_workspace_id();
alter table public.sales alter column workspace_id set default public.current_workspace_id();
alter table public.payments alter column workspace_id set default public.current_workspace_id();
alter table public.expenses alter column workspace_id set default public.current_workspace_id();
alter table public.goals alter column workspace_id set default public.current_workspace_id();
alter table public.budgets alter column workspace_id set default public.current_workspace_id();

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null default public.current_workspace_id() references public.workspaces(id) on delete cascade,
  type text not null check(type in ('business','personal')), name text not null,
  subcategories text[] not null default '{}', created_at timestamptz not null default now(),
  unique(workspace_id,type,name)
);
create table if not exists public.sale_templates (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null default public.current_workspace_id() references public.workspaces(id) on delete cascade,
  name text not null, base numeric(12,2) not null check(base>0), paid_percent integer not null default 50,
  iva_enabled boolean not null default true, irpf_enabled boolean not null default true,
  extra_rate numeric(6,3) not null default 0, description text default '', created_at timestamptz not null default now()
);
create table if not exists public.recurring_rules (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null default public.current_workspace_id() references public.workspaces(id) on delete cascade,
  name text not null, amount numeric(12,2) not null check(amount>0),
  type text not null check(type in ('business','personal')), category text not null, subcategory text default '',
  method text not null default 'Tarjeta', deductible boolean not null default false, description text default '',
  frequency text not null default 'monthly' check(frequency in ('monthly','yearly')),
  next_due date not null, active boolean not null default true, created_at timestamptz not null default now()
);

insert into public.categories(workspace_id,type,name,subcategories)
select w.id,v.type,v.name,v.subs from public.workspaces w cross join (values
 ('business','Suscripciones',array['Web','Diseño','Productividad']::text[]),('business','Fotografía',array['Fotógrafo','Edición']::text[]),
 ('business','Impresión QR',array['Tarjetas','Soportes']::text[]),('business','Equipamiento',array['Ordenador','Cámara','Accesorios']::text[]),
 ('business','Marketing',array['Publicidad','Redes']::text[]),('business','Otros',array[]::text[]),
 ('personal','Comida',array['Supermercado','Restaurantes']::text[]),('personal','Ropa',array[]::text[]),
 ('personal','Deporte',array['Gimnasio','Material']::text[]),('personal','Zapatillas',array[]::text[]),
 ('personal','Ocio y lujos',array[]::text[]),('personal','Transporte',array['Combustible','Público']::text[]),('personal','Otros',array[]::text[])
) as v(type,name,subs) on conflict(workspace_id,type,name) do nothing;


create or replace function public.reset_active_workspace_after_member_delete() returns trigger
language plpgsql security definer set search_path=public as $$
begin
  if (select active_workspace_id from public.profiles where id=old.user_id)=old.workspace_id then
    update public.profiles set active_workspace_id=(select workspace_id from public.workspace_members where user_id=old.user_id order by created_at limit 1) where id=old.user_id;
  end if;
  return old;
end $$;
drop trigger if exists on_workspace_member_deleted on public.workspace_members;
create trigger on_workspace_member_deleted after delete on public.workspace_members for each row execute function public.reset_active_workspace_after_member_delete();

create or replace function public.accept_workspace_invite(p_token uuid) returns uuid
language plpgsql security definer set search_path=public as $$
declare v_inv public.workspace_invitations; v_name text; v_email text;
begin
  select * into v_inv from public.workspace_invitations where token=p_token and accepted_at is null;
  if v_inv.id is null then raise exception 'INVITE_NOT_FOUND'; end if;
  select coalesce(raw_user_meta_data->>'name',''),coalesce(email,'') into v_name,v_email from auth.users where id=auth.uid();
  if lower(v_email)<>lower(v_inv.email) then raise exception 'INVITE_EMAIL_MISMATCH'; end if;
  insert into public.workspace_members(workspace_id,user_id,role,display_name,email)
  values(v_inv.workspace_id,auth.uid(),v_inv.role,v_name,v_email)
  on conflict(workspace_id,user_id) do update set role=excluded.role,display_name=excluded.display_name,email=excluded.email;
  update public.workspace_invitations set accepted_at=now() where id=v_inv.id;
  update public.profiles set active_workspace_id=v_inv.workspace_id where id=auth.uid();
  return v_inv.workspace_id;
end $$;

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$
declare v_workspace uuid;
begin
  insert into public.profiles(id,name,email) values(new.id,coalesce(new.raw_user_meta_data->>'name',''),coalesce(new.email,'')) on conflict(id) do update set email=excluded.email;
  insert into public.workspaces(owner_id,name) values(new.id,'Clario de '||coalesce(nullif(new.raw_user_meta_data->>'name',''),'Usuario')) returning id into v_workspace;
  insert into public.workspace_members(workspace_id,user_id,role,display_name,email) values(v_workspace,new.id,'owner',coalesce(new.raw_user_meta_data->>'name',''),coalesce(new.email,''));
  update public.profiles set active_workspace_id=v_workspace where id=new.id;
  insert into public.categories(workspace_id,type,name) values
   (v_workspace,'business','Suscripciones'),(v_workspace,'business','Fotografía'),(v_workspace,'business','Impresión QR'),
   (v_workspace,'business','Equipamiento'),(v_workspace,'business','Marketing'),(v_workspace,'business','Otros'),
   (v_workspace,'personal','Comida'),(v_workspace,'personal','Ropa'),(v_workspace,'personal','Deporte'),
   (v_workspace,'personal','Zapatillas'),(v_workspace,'personal','Ocio y lujos'),(v_workspace,'personal','Transporte'),(v_workspace,'personal','Otros');
  return new;
end $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

alter table public.workspaces enable row level security;
alter table public.workspace_members enable row level security;
alter table public.workspace_invitations enable row level security;
alter table public.categories enable row level security;
alter table public.sale_templates enable row level security;
alter table public.recurring_rules enable row level security;

-- Replace owner-only policies with workspace-aware policies.
do $$ declare t text; begin
  foreach t in array array['clients','sales','payments','expenses','goals','budgets'] loop
    execute format('drop policy if exists %I on public.%I',t||'_own',t);
    execute format('drop policy if exists %I on public.%I',t||'_view',t);
    execute format('drop policy if exists %I on public.%I',t||'_insert',t);
    execute format('drop policy if exists %I on public.%I',t||'_update',t);
    execute format('drop policy if exists %I on public.%I',t||'_delete',t);
    execute format('create policy %I on public.%I for select using (public.can_view_workspace(workspace_id))',t||'_view',t);
    execute format('create policy %I on public.%I for insert with check (public.can_edit_workspace(workspace_id))',t||'_insert',t);
    execute format('create policy %I on public.%I for update using (public.can_edit_workspace(workspace_id)) with check (public.can_edit_workspace(workspace_id))',t||'_update',t);
    execute format('create policy %I on public.%I for delete using (public.can_edit_workspace(workspace_id))',t||'_delete',t);
  end loop;
end $$;

drop policy if exists workspaces_view on public.workspaces; create policy workspaces_view on public.workspaces for select using(public.can_view_workspace(id));
drop policy if exists workspaces_update on public.workspaces; create policy workspaces_update on public.workspaces for update using(public.can_manage_workspace(id));
drop policy if exists members_view on public.workspace_members; create policy members_view on public.workspace_members for select using(public.can_view_workspace(workspace_id));
drop policy if exists members_manage on public.workspace_members; create policy members_manage on public.workspace_members for all using(public.can_manage_workspace(workspace_id)) with check(public.can_manage_workspace(workspace_id));
drop policy if exists invites_manage on public.workspace_invitations; create policy invites_manage on public.workspace_invitations for all using(public.can_manage_workspace(workspace_id)) with check(public.can_manage_workspace(workspace_id));

do $$ declare t text; begin
  foreach t in array array['categories','sale_templates','recurring_rules'] loop
    execute format('drop policy if exists %I on public.%I',t||'_view',t);
    execute format('drop policy if exists %I on public.%I',t||'_manage',t);
    execute format('create policy %I on public.%I for select using (public.can_view_workspace(workspace_id))',t||'_view',t);
    execute format('create policy %I on public.%I for all using (public.can_edit_workspace(workspace_id)) with check (public.can_edit_workspace(workspace_id))',t||'_manage',t);
  end loop;
end $$;

drop policy if exists receipts_read_own on storage.objects;
drop policy if exists receipts_read_workspace on storage.objects;
drop policy if exists receipts_insert_workspace on storage.objects;
drop policy if exists receipts_update_workspace on storage.objects;
drop policy if exists receipts_delete_workspace on storage.objects;
drop policy if exists receipts_insert_own on storage.objects;
drop policy if exists receipts_update_own on storage.objects;
drop policy if exists receipts_delete_own on storage.objects;
create policy receipts_read_workspace on storage.objects for select using(bucket_id='receipts' and ((storage.foldername(name))[1]=auth.uid()::text or public.can_view_workspace(((storage.foldername(name))[1])::uuid)));
create policy receipts_insert_workspace on storage.objects for insert with check(bucket_id='receipts' and ((storage.foldername(name))[1]=auth.uid()::text or public.can_edit_workspace(((storage.foldername(name))[1])::uuid)));
create policy receipts_update_workspace on storage.objects for update using(bucket_id='receipts' and ((storage.foldername(name))[1]=auth.uid()::text or public.can_edit_workspace(((storage.foldername(name))[1])::uuid)));
create policy receipts_delete_workspace on storage.objects for delete using(bucket_id='receipts' and ((storage.foldername(name))[1]=auth.uid()::text or public.can_edit_workspace(((storage.foldername(name))[1])::uuid)));

create unique index if not exists budgets_workspace_category_unique on public.budgets(workspace_id,type,category);
create index if not exists members_workspace_idx on public.workspace_members(workspace_id,user_id);
create index if not exists categories_workspace_idx on public.categories(workspace_id,type);
create index if not exists templates_workspace_idx on public.sale_templates(workspace_id);
create index if not exists recurring_workspace_idx on public.recurring_rules(workspace_id,next_due);
