(function(){
  'use strict';
  var config=window.CLARIO_CONFIG||{};
  if(config.mode!=='supabase')return;
  var previousFetch=window.fetch.bind(window);
  var base=String(config.supabaseUrl||'').replace(/\/$/,'');
  var anon=config.supabaseAnonKey||'';
  var tokenKey='clario_supabase_session';
  var workspaceCache=null;
  function response(status,body){return new Response(JSON.stringify(body),{status:status,headers:{'Content-Type':'application/json'}});}
  function sessionValue(){try{return JSON.parse(localStorage.getItem(tokenKey)||'null');}catch(e){return null;}}
  async function ensureSession(){var s=sessionValue();if(s&&s.access_token&&(!s.expires_at||s.expires_at*1000>Date.now()+60000))return s;await previousFetch('/api/session',{headers:{}});s=sessionValue();if(!s||!s.access_token)throw Object.assign(new Error('AUTH_REQUIRED'),{status:401});return s;}
  async function direct(table,query,options){var s=await ensureSession();var res=await previousFetch(base+'/rest/v1/'+table+(query?'?'+query:''),Object.assign({},options||{},{headers:Object.assign({apikey:anon,Authorization:'Bearer '+s.access_token,'Content-Type':'application/json'},options&&options.headers||{})}));if(!res.ok)throw Object.assign(new Error(await res.text()||'SUPABASE_ERROR'),{status:res.status});var text=await res.text();return text?JSON.parse(text):null;}
  async function rpc(name,body){var s=await ensureSession();var res=await previousFetch(base+'/rest/v1/rpc/'+name,{method:'POST',headers:{apikey:anon,Authorization:'Bearer '+s.access_token,'Content-Type':'application/json'},body:JSON.stringify(body||{})});if(!res.ok)throw Object.assign(new Error(await res.text()||'RPC_ERROR'),{status:res.status});var text=await res.text();return text?JSON.parse(text):null;}
  async function bodyOf(init){return init&&init.body?JSON.parse(init.body):{};}
  async function workspace(){if(workspaceCache)return workspaceCache;var s=await ensureSession();var profiles=await direct('profiles','id=eq.'+s.user.id+'&select=active_workspace_id');var id=profiles[0]&&profiles[0].active_workspace_id;if(!id){var spaces=await direct('workspaces','select=id&order=created_at.asc&limit=1');id=spaces[0]&&spaces[0].id;}workspaceCache=id;window.CLARIO_WORKSPACE_ID=id;return id;}
  function addPeriod(date,frequency){var d=new Date(String(date)+'T12:00:00');if(frequency==='yearly')d.setFullYear(d.getFullYear()+1);else d.setMonth(d.getMonth()+1);return d.toISOString().slice(0,10);}
  async function extendedDashboard(){var baseData=await previousFetch('/api/dashboard').then(function(r){if(!r.ok)throw Object.assign(new Error('DASHBOARD_ERROR'),{status:r.status});return r.json();});var wid=await workspace();var q='workspace_id=eq.'+wid;var extra=await Promise.all([
    direct('workspaces','id=eq.'+wid+'&select=*'),direct('workspace_members',q+'&select=*&order=created_at.asc'),
    direct('workspace_invitations',q+'&accepted_at=is.null&select=*&order=created_at.desc'),direct('categories',q+'&select=*&order=type,name'),
    direct('sale_templates',q+'&select=*&order=created_at.desc'),direct('recurring_rules',q+'&select=*&order=next_due.asc')
  ]);var s=sessionValue();var me=extra[1].find(function(m){return m.user_id===s.user.id;});baseData.workspace=extra[0][0]||{id:wid,name:'Clario'};baseData.members=extra[1];baseData.invitations=extra[2];baseData.categories=extra[3];baseData.templates=extra[4];baseData.recurringRules=extra[5];baseData.currentRole=me?me.role:'viewer';return baseData;}
  async function createRecurringFromExpense(b){if(!b.recurring)return;var wid=await workspace();var start=b.date||new Date().toISOString().slice(0,10);await direct('recurring_rules','',{method:'POST',body:JSON.stringify({workspace_id:wid,name:b.name,amount:b.amount,type:b.type,category:b.category||'Otros',subcategory:b.subcategory||'',method:b.method||'Tarjeta',deductible:Boolean(b.deductible),description:b.description||'',frequency:b.frequency||'monthly',next_due:addPeriod(start,b.frequency||'monthly')})});}
  async function handle(path,init){var method=(init&&init.method||'GET').toUpperCase();var b=await bodyOf(init);var wid,match,rows;
    if(path==='/api/dashboard'&&method==='GET')return response(200,await extendedDashboard());
    if(path==='/api/expenses'&&method==='POST'){var saved=await previousFetch(path,init);if(saved.ok)await createRecurringFromExpense(b);return saved;}
    if(path==='/api/budgets'&&method==='POST'){wid=await workspace();for(var item of b.budgets||[]){if(Number(item.limit)>0)await direct('budgets','on_conflict=workspace_id,type,category',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({workspace_id:wid,type:item.type,category:item.category,budget_limit:item.limit,warning_percent:item.warningPercent||80,period:'monthly'})});else await direct('budgets','workspace_id=eq.'+wid+'&type=eq.'+encodeURIComponent(item.type)+'&category=eq.'+encodeURIComponent(item.category),{method:'DELETE'});}return response(200,{ok:true});}
    match=path.match(/^\/api\/clients\/(\d+)$/);if(match&&method==='PATCH'){rows=await direct('clients','id=eq.'+match[1],{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify({name:b.name,contact_name:b.contactName||'',phone:b.phone||'',email:b.email||'',address:b.address||'',tax_id:b.taxId||'',notes:b.notes||''})});return response(200,{ok:true,client:rows[0]});}if(match&&method==='DELETE'){await direct('clients','id=eq.'+match[1],{method:'DELETE'});return response(200,{ok:true});}
    match=path.match(/^\/api\/goals\/(\d+)$/);if(match&&method==='PATCH'){await direct('goals','id=eq.'+match[1],{method:'PATCH',body:JSON.stringify({name:b.name,target:b.target,current:b.current||0,term:b.term||'medium'})});return response(200,{ok:true});}if(match&&method==='DELETE'){await direct('goals','id=eq.'+match[1],{method:'DELETE'});return response(200,{ok:true});}
    if(path==='/api/categories'&&method==='POST'){wid=await workspace();rows=await direct('categories','',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({workspace_id:wid,type:b.type,name:b.name,subcategories:b.subcategories||[]})});return response(201,{ok:true,id:rows[0].id});}
    match=path.match(/^\/api\/categories\/(\d+)$/);if(match&&method==='PATCH'){await direct('categories','id=eq.'+match[1],{method:'PATCH',body:JSON.stringify({name:b.name,subcategories:b.subcategories||[]})});return response(200,{ok:true});}if(match&&method==='DELETE'){await direct('categories','id=eq.'+match[1],{method:'DELETE'});return response(200,{ok:true});}
    if(path==='/api/templates'&&method==='POST'){wid=await workspace();rows=await direct('sale_templates','',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({workspace_id:wid,name:b.name,base:b.base,paid_percent:b.paidPercent||50,iva_enabled:b.ivaEnabled!==false,irpf_enabled:b.irpfEnabled!==false,extra_rate:b.extraRate||0,description:b.description||''})});return response(201,{ok:true,id:rows[0].id});}
    match=path.match(/^\/api\/templates\/(\d+)$/);if(match&&method==='PATCH'){await direct('sale_templates','id=eq.'+match[1],{method:'PATCH',body:JSON.stringify({name:b.name,base:b.base,paid_percent:b.paidPercent||50,iva_enabled:b.ivaEnabled!==false,irpf_enabled:b.irpfEnabled!==false,extra_rate:b.extraRate||0,description:b.description||''})});return response(200,{ok:true});}if(match&&method==='DELETE'){await direct('sale_templates','id=eq.'+match[1],{method:'DELETE'});return response(200,{ok:true});}
    match=path.match(/^\/api\/recurring\/(\d+)\/(confirm|skip)$/);if(match&&method==='POST'){rows=await direct('recurring_rules','id=eq.'+match[1]+'&select=*');var rule=rows[0];if(!rule)return response(404,{error:'NOT_FOUND'});if(match[2]==='confirm')await direct('expenses','',{method:'POST',body:JSON.stringify({workspace_id:rule.workspace_id,name:rule.name,amount:rule.amount,type:rule.type,category:rule.category,subcategory:rule.subcategory,method:rule.method,deductible:rule.deductible,description:rule.description,recurring:true,confirmed_at:new Date().toISOString().slice(0,10)})});await direct('recurring_rules','id=eq.'+match[1],{method:'PATCH',body:JSON.stringify({next_due:addPeriod(rule.next_due,rule.frequency)})});return response(200,{ok:true});}
    match=path.match(/^\/api\/recurring\/(\d+)$/);if(match&&method==='DELETE'){await direct('recurring_rules','id=eq.'+match[1],{method:'DELETE'});return response(200,{ok:true});}
    if(path==='/api/team/invitations'&&method==='POST'){wid=await workspace();rows=await direct('workspace_invitations','',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({workspace_id:wid,email:String(b.email||'').trim().toLowerCase(),role:b.role==='editor'?'editor':'viewer'})});return response(201,{ok:true,invitation:rows[0]});}
    if(path==='/api/team/accept'&&method==='POST'){var accepted=await rpc('accept_workspace_invite',{p_token:b.token});workspaceCache=accepted;return response(200,{ok:true,workspaceId:accepted});}
    match=path.match(/^\/api\/team\/members\/(\d+)$/);if(match&&method==='PATCH'){rows=await direct('workspace_members','id=eq.'+match[1]+'&select=*');if(!rows[0]||rows[0].role==='owner')return response(403,{error:'OWNER_PROTECTED'});await direct('workspace_members','id=eq.'+match[1],{method:'PATCH',body:JSON.stringify({role:b.role==='editor'?'editor':'viewer'})});return response(200,{ok:true});}if(match&&method==='DELETE'){rows=await direct('workspace_members','id=eq.'+match[1]+'&select=*');if(!rows[0]||rows[0].role==='owner')return response(403,{error:'OWNER_PROTECTED'});await direct('workspace_members','id=eq.'+match[1],{method:'DELETE'});return response(200,{ok:true});}
    return null;
  }
  window.fetch=async function(input,init){var value=typeof input==='string'?input:input.url;if(value.startsWith('/api/')){try{var handled=await handle(value.split('?')[0],init||{});if(handled)return handled;}catch(error){return response(error.status||500,{error:error.message||'ADVANCED_API_ERROR'});}}return previousFetch(input,init);};
})();
